import type { StoreApp } from "./useSystemData";

export type StoreCategory = "discover" | "browser" | "office" | "social" | "media" | "utilities" | "development" | "creative" | "games";
export type StoreSectionId = "domestic" | "setup" | "productivity" | "creative" | "development" | "games";

export interface CuratedApp extends StoreApp {
  category: Exclude<StoreCategory, "discover">;
  description: string;
  publisher: string;
  section: StoreSectionId;
  icon?: string;
  iconUrl?: string;
}

type CatalogRow = [string, string, CuratedApp["category"], string, string, StoreSectionId, string?];

const rows: CatalogRow[] = [
  ["Tencent.WeChat", "微信", "social", "聊天、通话与文件传输", "腾讯", "domestic", "thesvg-color:wechat"],
  ["Tencent.QQ.NT", "QQ", "social", "聊天、群组与文件分享", "腾讯", "domestic", "thesvg-color:qq"],
  ["Tencent.WeCom", "企业微信", "social", "企业沟通与客户联系", "腾讯", "domestic", "simple-icons:wechat"],
  ["ByteDance.Feishu", "飞书", "office", "团队沟通与协作", "北京飞书科技", "domestic"],
  ["Tencent.TencentMeeting", "腾讯会议", "office", "在线会议与屏幕共享", "腾讯", "domestic", "tdesign:logo-tencentmeeting-filled"],
  ["Kingsoft.WPSOffice.CN", "WPS Office", "office", "文档、表格、演示与 PDF", "金山办公", "domestic"],
  ["NetEase.CloudMusic", "网易云音乐", "media", "音乐播放与歌单管理", "网易", "domestic", "thesvg-color:netease-cloud-music"],
  ["Tencent.QQMusic", "QQ 音乐", "media", "在线音乐与歌单", "腾讯", "domestic"],
  ["Baidu.BaiduNetdisk", "百度网盘", "utilities", "文件存储、同步与分享", "百度", "domestic", "thesvg-color:baiducloud"],
  ["Bilibili.Livehime", "哔哩哔哩直播姬", "media", "直播与录制工具", "哔哩哔哩", "domestic", "simple-icons:bilibili"],
  ["ByteDance.Douyin", "抖音", "media", "短视频与直播", "字节跳动", "domestic", "simple-icons:tiktok"],
  ["liule.Snipaste", "Snipaste", "utilities", "截图、贴图与标注", "Snipaste", "domestic"],
  ["Xmind.Xmind", "XMind", "office", "思维导图与头脑风暴", "XMind", "productivity", "arcticons:xmind"],

  ["Google.Chrome", "Google Chrome", "browser", "快速、安全的网页浏览器", "Google", "setup", "logos:chrome"],
  ["Mozilla.Firefox", "Firefox", "browser", "开放且注重隐私的浏览器", "Mozilla", "setup", "logos:firefox"],
  ["Brave.Brave", "Brave", "browser", "内置隐私保护的浏览器", "Brave", "setup", "logos:brave"],
  ["Opera.Opera", "Opera", "browser", "内置实用功能的浏览器", "Opera", "setup", "logos:opera"],
  ["Vivaldi.Vivaldi", "Vivaldi", "browser", "高度可定制的浏览器", "Vivaldi", "setup", "logos:vivaldi-icon"],
  ["Microsoft.Edge", "Microsoft Edge", "browser", "适用于 Windows 的浏览器", "Microsoft", "setup", "logos:microsoft-edge"],
  ["TorProject.TorBrowser", "Tor Browser", "browser", "重视匿名访问的浏览器", "Tor Project", "setup", "logos:tor-browser"],
  ["LibreWolf.LibreWolf", "LibreWolf", "browser", "注重隐私的 Firefox 分支", "LibreWolf", "setup", "simple-icons:librewolf"],
  ["Waterfox.Waterfox", "Waterfox", "browser", "独立的 Firefox 系浏览器", "Waterfox", "setup", "simple-icons:waterfox"],
  ["Zen-Team.Zen-Browser", "Zen Browser", "browser", "现代化的 Firefox 系浏览器", "Zen Team", "setup", "simple-icons:zenbrowser"],
  ["qutebrowser.qutebrowser", "qutebrowser", "browser", "键盘驱动的轻量浏览器", "qutebrowser", "setup", "simple-icons:qutebrowser"],
  ["MullvadVPN.MullvadBrowser", "Mullvad Browser", "browser", "侧重隐私防护的浏览器", "Mullvad", "setup", "simple-icons:mullvad"],
  ["Maxthon.Maxthon", "傲游浏览器", "browser", "多功能网页浏览器", "Maxthon", "setup"],
  ["MoonchildProductions.PaleMoon", "Pale Moon", "browser", "轻量且可定制的浏览器", "Moonchild Productions", "setup"],
  ["Mozilla.SeaMonkey", "SeaMonkey", "browser", "浏览器与邮件工具套件", "SeaMonkey Council", "setup"],
  ["SRWare.Iron", "SRWare Iron", "browser", "注重隐私的 Chromium 浏览器", "SRWare", "setup"],
  ["CentStudio.CentBrowser", "百分浏览器", "browser", "面向效率的 Chromium 浏览器", "Cent Studio", "setup"],
  ["eloston.ungoogled-chromium", "ungoogled-chromium", "browser", "精简 Google 服务的 Chromium", "Eloston", "setup", "simple-icons:chromium"],
  ["TheBrowserCompany.Arc", "Arc", "browser", "以空间管理为特色的浏览器", "The Browser Company", "setup", "simple-icons:arc"],
  ["KDE.Falkon", "Falkon", "browser", "KDE 轻量网页浏览器", "KDE", "setup", "simple-icons:kde"],

  ["7zip.7zip", "7-Zip", "utilities", "文件压缩与解压", "Igor Pavlov", "setup", "thesvg-color:7zip"],
  ["RARLab.WinRAR", "WinRAR", "utilities", "压缩文件管理工具", "RARLAB", "setup", "simple-icons:winrar"],
  ["Bandisoft.Bandizip", "Bandizip", "utilities", "快速压缩与解压", "Bandisoft", "setup"],
  ["Giorgiotani.Peazip", "PeaZip", "utilities", "开源压缩文件管理器", "PeaZip", "setup", "simple-icons:peazip"],
  ["voidtools.Everything", "Everything", "utilities", "快速搜索本机文件", "voidtools", "setup"],
  ["Microsoft.PowerToys", "PowerToys", "utilities", "增强 Windows 效率工具集", "Microsoft", "setup", "logos:microsoft-icon"],
  ["Microsoft.WindowsTerminal", "Windows Terminal", "utilities", "现代化命令行终端", "Microsoft", "setup", "logos:terminal"],
  ["CPUID.CPU-Z", "CPU-Z", "utilities", "查看处理器与硬件信息", "CPUID", "setup"],
  ["TechPowerUp.GPU-Z", "GPU-Z", "utilities", "查看显卡与传感器信息", "TechPowerUp", "setup"],
  ["CrystalDewWorld.CrystalDiskInfo", "CrystalDiskInfo", "utilities", "查看磁盘健康状态", "Crystal Dew World", "setup"],
  ["CrystalDewWorld.CrystalDiskMark", "CrystalDiskMark", "utilities", "测试磁盘读写性能", "Crystal Dew World", "setup"],
  ["Rufus.Rufus", "Rufus", "utilities", "制作可启动 U 盘", "Rufus", "setup", "simple-icons:rufus"],
  ["Balena.Etcher", "balenaEtcher", "utilities", "写入系统镜像到存储设备", "Balena", "setup", "logos:balena"],
  ["Ventoy.Ventoy", "Ventoy", "utilities", "制作多镜像启动盘", "Ventoy", "setup"],
  ["LocalSend.LocalSend", "LocalSend", "utilities", "局域网跨设备传输文件", "LocalSend", "setup", "simple-icons:localsend"],
  ["ShareX.ShareX", "ShareX", "utilities", "截图、录屏与分享", "ShareX", "setup", "simple-icons:sharex"],
  ["Greenshot.Greenshot", "Greenshot", "utilities", "轻量截图与标注", "Greenshot", "setup"],
  ["Flameshot.Flameshot", "Flameshot", "utilities", "开源截图与标注", "Flameshot", "setup", "simple-icons:flameshot"],
  ["Ditto.Ditto", "Ditto", "utilities", "剪贴板历史管理", "Ditto", "setup"],
  ["AutoHotkey.AutoHotkey", "AutoHotkey", "utilities", "键盘鼠标自动化", "AutoHotkey", "setup", "simple-icons:autohotkey"],
  ["BleachBit.BleachBit", "BleachBit", "utilities", "清理临时文件与缓存", "BleachBit", "setup", "simple-icons:bleachbit"],
  ["AntibodySoftware.WizTree", "WizTree", "utilities", "快速分析磁盘空间", "Antibody Software", "setup"],
  ["WinDirStat.WinDirStat", "WinDirStat", "utilities", "可视化分析磁盘占用", "WinDirStat", "setup"],
  ["WinSCP.WinSCP", "WinSCP", "utilities", "SFTP 与 SCP 文件传输", "WinSCP", "setup", "simple-icons:winscp"],
  ["PuTTY.PuTTY", "PuTTY", "utilities", "SSH 与串口客户端", "PuTTY", "setup", "simple-icons:putty"],
  ["qBittorrent.qBittorrent", "qBittorrent", "utilities", "开源下载工具", "qBittorrent", "setup", "simple-icons:qbittorrent"],
  ["WiresharkFoundation.Wireshark", "Wireshark", "utilities", "网络协议分析工具", "Wireshark Foundation", "setup", "simple-icons:wireshark"],

  ["Microsoft.Office", "Microsoft 365", "office", "文档、表格与演示办公套件", "Microsoft", "productivity", "logos:microsoft-icon"],
  ["TheDocumentFoundation.LibreOffice", "LibreOffice", "office", "开源办公套件", "The Document Foundation", "productivity", "simple-icons:libreoffice"],
  ["ONLYOFFICE.DesktopEditors", "ONLYOFFICE", "office", "文档协作与编辑套件", "ONLYOFFICE", "productivity", "simple-icons:onlyoffice"],
  ["Apache.OpenOffice", "OpenOffice", "office", "开源办公套件", "Apache", "productivity", "simple-icons:apacheopenoffice"],
  ["Notion.Notion", "Notion", "office", "笔记、知识库与协作", "Notion", "productivity", "logos:notion"],
  ["Obsidian.Obsidian", "Obsidian", "office", "本地 Markdown 知识库", "Obsidian", "productivity", "logos:obsidian-icon"],
  ["Joplin.Joplin", "Joplin", "office", "开源笔记与待办管理", "Joplin", "productivity", "simple-icons:joplin"],
  ["Evernote.Evernote", "Evernote", "office", "笔记与资料整理", "Evernote", "productivity", "logos:evernote"],
  ["Logseq.Logseq", "Logseq", "office", "大纲式知识管理", "Logseq", "productivity", "simple-icons:logseq"],
  ["Anki.Anki", "Anki", "office", "间隔记忆卡片工具", "Anki", "productivity", "simple-icons:anki"],
  ["JGraph.Draw", "draw.io", "office", "流程图与图表制作", "JGraph", "productivity", "simple-icons:diagramsdotnet"],
  ["Miro.Miro", "Miro", "office", "团队在线白板", "Miro", "productivity", "logos:miro-icon"],
  ["SlackTechnologies.Slack", "Slack", "office", "团队沟通与协作", "Slack", "productivity", "logos:slack-icon"],
  ["Microsoft.Teams", "Microsoft Teams", "office", "会议、聊天与团队协作", "Microsoft", "productivity", "logos:microsoft-teams"],
  ["Zoom.Zoom", "Zoom", "office", "视频会议与在线协作", "Zoom", "productivity", "logos:zoom-icon"],
  ["Cisco.Webex", "Webex", "office", "企业会议与协作", "Cisco", "productivity", "simple-icons:webex"],
  ["Doist.Todoist", "Todoist", "office", "任务与项目管理", "Doist", "productivity", "logos:todoist-icon"],
  ["Appest.TickTick", "滴答清单", "office", "待办、日历与专注管理", "Appest", "productivity", "simple-icons:ticktick"],
  ["Adobe.Acrobat.Reader.64-bit", "Adobe Acrobat Reader", "office", "PDF 阅读、批注与签名", "Adobe", "productivity", "simple-icons:adobeacrobatreader"],
  ["Foxit.FoxitReader", "福昕 PDF 阅读器", "office", "PDF 阅读与批注", "Foxit", "productivity", "simple-icons:foxitreader"],

  ["Telegram.TelegramDesktop", "Telegram", "social", "即时通讯与群组", "Telegram", "productivity", "logos:telegram"],
  ["Discord.Discord", "Discord", "social", "社区语音与文字聊天", "Discord", "productivity", "logos:discord-icon"],
  ["Rakuten.Viber", "Viber", "social", "即时通讯与通话", "Rakuten", "productivity", "simple-icons:viber"],
  ["OpenWhisperSystems.Signal", "Signal", "social", "注重隐私的即时通讯", "Signal", "productivity", "logos:signal"],
  ["Mozilla.Thunderbird", "Thunderbird", "social", "开源邮件与日历客户端", "Mozilla", "productivity", "logos:thunderbird"],
  ["eMClient.eMClient", "eM Client", "social", "邮件、日历与联系人", "eM Client", "productivity"],
  ["Element.Element", "Element", "social", "基于 Matrix 的安全通讯", "Element", "productivity", "simple-icons:element"],
  ["Ferdium.Ferdium", "Ferdium", "social", "集中管理多个通讯服务", "Ferdium", "productivity", "simple-icons:ferdium"],
  ["StefanMalzner.Franz", "Franz", "social", "多服务消息聚合客户端", "Franz", "productivity", "simple-icons:franz"],
  ["Mattermost.MattermostDesktop", "Mattermost", "social", "团队消息与协作", "Mattermost", "productivity", "logos:mattermost-icon"],
  ["RocketChat.RocketChat", "Rocket.Chat", "social", "开源团队通讯", "Rocket.Chat", "productivity", "simple-icons:rocketdotchat"],
  ["Zulip.Zulip", "Zulip", "social", "按主题组织的团队通讯", "Zulip", "productivity", "simple-icons:zulip"],
  ["Beeper.Beeper", "Beeper", "social", "集中管理多个聊天服务", "Beeper", "productivity", "simple-icons:beeper"],
  ["Rambox.Rambox.Community", "Rambox", "social", "工作通讯应用聚合器", "Rambox", "productivity", "simple-icons:rambox"],
  ["Station.Station", "Station", "social", "集中管理网页工作应用", "Station", "productivity"],
  ["Shift.Shift", "Shift", "social", "邮件与工作应用聚合器", "Shift", "productivity"],
  ["CeruleanStudios.Trillian", "Trillian", "social", "跨平台即时通讯", "Cerulean Studios", "productivity"],

  ["VideoLAN.VLC", "VLC", "media", "本地影音播放", "VideoLAN", "creative", "thesvg-color:vlc-media-player"],
  ["Daum.PotPlayer", "PotPlayer", "media", "本地高清视频播放器", "Kakao", "creative"],
  ["Spotify.Spotify", "Spotify", "media", "音乐与播客播放", "Spotify", "creative", "logos:spotify-icon"],
  ["Apple.iTunes", "iTunes", "media", "音乐与 Apple 设备管理", "Apple", "creative", "logos:itunes"],
  ["OBSProject.OBSStudio", "OBS Studio", "media", "直播与屏幕录制", "OBS Project", "creative", "logos:obs"],
  ["Audacity.Audacity", "Audacity", "media", "开源音频录制与编辑", "Audacity", "creative", "logos:audacity"],
  ["HandBrake.HandBrake", "HandBrake", "media", "视频转码与压缩", "HandBrake", "creative", "simple-icons:handbrake"],
  ["Gyan.FFmpeg", "FFmpeg", "media", "音视频处理工具集", "FFmpeg", "creative", "logos:ffmpeg-icon"],
  ["CodecGuide.K-LiteCodecPack.Full", "K-Lite Codec Pack", "media", "Windows 音视频解码组件", "Codec Guide", "creative"],
  ["PeterPawlowski.foobar2000", "foobar2000", "media", "轻量本地音乐播放器", "Peter Pawlowski", "creative", "simple-icons:foobar2000"],
  ["AIMP.AIMP", "AIMP", "media", "本地音乐播放器", "AIMP", "creative"],
  ["mpv.net", "mpv.net", "media", "基于 mpv 的播放器", "mpv.net", "creative", "simple-icons:mpv"],
  ["Jellyfin.JellyfinMediaPlayer", "Jellyfin Media Player", "media", "家庭媒体库客户端", "Jellyfin", "creative", "simple-icons:jellyfin"],
  ["XBMCFoundation.Kodi", "Kodi", "media", "家庭影音中心", "Kodi", "creative", "simple-icons:kodi"],
  ["ch.LosslessCut", "LosslessCut", "media", "无损视频快速剪切", "LosslessCut", "creative"],
  ["KDE.Kdenlive", "Kdenlive", "media", "开源视频编辑器", "KDE", "creative", "simple-icons:kdenlive"],
  ["Meltytech.Shotcut", "Shotcut", "media", "开源跨平台视频编辑器", "Meltytech", "creative"],
  ["OpenShot.OpenShot", "OpenShot", "media", "易用的开源视频编辑器", "OpenShot", "creative", "simple-icons:openshot"],

  ["BlenderFoundation.Blender", "Blender", "creative", "三维建模、动画与渲染", "Blender Foundation", "creative", "logos:blender"],
  ["GIMP.GIMP.3", "GIMP", "creative", "开源图像编辑器", "GIMP", "creative", "logos:gimp"],
  ["Inkscape.Inkscape", "Inkscape", "creative", "开源矢量图形编辑器", "Inkscape", "creative", "logos:inkscape"],
  ["KDE.Krita", "Krita", "creative", "数字绘画与插画", "KDE", "creative", "simple-icons:krita"],
  ["Figma.Figma", "Figma", "creative", "界面设计与协作", "Figma", "creative", "logos:figma"],
  ["Canva.Canva", "Canva", "creative", "在线视觉设计工具", "Canva", "creative", "logos:canva"],
  ["Adobe.CreativeCloud", "Adobe Creative Cloud", "creative", "Adobe 创意应用管理", "Adobe", "creative", "simple-icons:adobecreativecloud"],
  ["FreeCAD.FreeCAD", "FreeCAD", "creative", "开源参数化三维 CAD", "FreeCAD", "creative", "simple-icons:freecad"],
  ["Prusa3D.PrusaSlicer", "PrusaSlicer", "creative", "三维打印切片工具", "Prusa Research", "creative", "simple-icons:prusa"],
  ["Ultimaker.Cura", "UltiMaker Cura", "creative", "三维打印切片工具", "UltiMaker", "creative", "simple-icons:ultimaker"],
  ["darktable.darktable", "darktable", "creative", "摄影工作流与 RAW 处理", "darktable", "creative", "simple-icons:darktable"],
  ["RawTherapee.RawTherapee", "RawTherapee", "creative", "RAW 照片处理工具", "RawTherapee", "creative", "simple-icons:rawtherapee"],
  ["KDE.digiKam", "digiKam", "creative", "照片管理与编辑", "KDE", "creative", "simple-icons:digikam"],
  ["Pencil2D.Pencil", "Pencil2D", "creative", "二维手绘动画", "Pencil2D", "creative"],
  ["DWANGO.OpenToonz", "OpenToonz", "creative", "二维动画制作", "OpenToonz", "creative"],
  ["GodotEngine.GodotEngine", "Godot Engine", "creative", "开源游戏与互动内容引擎", "Godot Engine", "creative", "logos:godot-icon"],
  ["Unity.UnityHub", "Unity Hub", "creative", "管理 Unity 编辑器与项目", "Unity", "creative", "logos:unity"],
  ["LMMS.LMMS", "LMMS", "creative", "开源数字音乐制作", "LMMS", "creative", "simple-icons:lmms"],
  ["OpenSCAD.OpenSCAD", "OpenSCAD", "creative", "代码驱动的三维建模", "OpenSCAD", "creative", "simple-icons:openscad"],
  ["Scribus.Scribus", "Scribus", "creative", "开源桌面出版工具", "Scribus", "creative", "simple-icons:scribus"],

  ["Microsoft.VisualStudioCode", "Visual Studio Code", "development", "轻量代码编辑器", "Microsoft", "development", "logos:visual-studio-code"],
  ["Git.Git", "Git", "development", "分布式版本控制工具", "Git", "development", "logos:git"],
  ["GitHub.GitHubDesktop", "GitHub Desktop", "development", "GitHub 桌面客户端", "GitHub", "development", "logos:github-icon"],
  ["JetBrains.Toolbox", "JetBrains Toolbox", "development", "管理 JetBrains 开发工具", "JetBrains", "development", "logos:jetbrains"],
  ["SublimeHQ.SublimeText.4", "Sublime Text", "development", "快速代码与文本编辑器", "Sublime HQ", "development", "logos:sublimetext-icon"],
  ["Notepad++.Notepad++", "Notepad++", "development", "轻量文本与代码编辑器", "Notepad++", "development", "simple-icons:notepadplusplus"],
  ["Microsoft.VisualStudio.2022.Community", "Visual Studio Community", "development", "完整的 Windows 开发环境", "Microsoft", "development", "logos:visual-studio"],
  ["Python.Python.3.13", "Python 3", "development", "Python 编程语言运行时", "Python Software Foundation", "development", "logos:python"],
  ["OpenJS.NodeJS.LTS", "Node.js LTS", "development", "JavaScript 运行时", "OpenJS Foundation", "development", "logos:nodejs-icon"],
  ["Oracle.JDK.21", "Oracle JDK 21", "development", "Java 开发工具包", "Oracle", "development", "logos:java"],
  ["EclipseAdoptium.Temurin.21.JDK", "Temurin JDK 21", "development", "开源 Java 开发工具包", "Eclipse Adoptium", "development", "logos:adoptium"],
  ["GoLang.Go", "Go", "development", "Go 编程语言工具链", "Go Team", "development", "logos:go"],
  ["Rustlang.Rustup", "Rustup", "development", "Rust 工具链管理器", "Rust Project", "development", "logos:rust"],
  ["Docker.DockerDesktop", "Docker Desktop", "development", "容器开发与管理", "Docker", "development", "logos:docker-icon"],
  ["Postman.Postman", "Postman", "development", "API 设计与调试", "Postman", "development", "logos:postman-icon"],
  ["Insomnia.Insomnia", "Insomnia", "development", "API 调试客户端", "Kong", "development", "logos:insomnia"],
  ["DBeaver.DBeaver.Community", "DBeaver Community", "development", "通用数据库客户端", "DBeaver", "development", "simple-icons:dbeaver"],
  ["MongoDB.Compass.Full", "MongoDB Compass", "development", "MongoDB 图形客户端", "MongoDB", "development", "logos:mongodb-icon"],
  ["RedisInsight.RedisInsight", "Redis Insight", "development", "Redis 图形管理工具", "Redis", "development", "logos:redis"],
  ["Axosoft.GitKraken", "GitKraken", "development", "Git 图形客户端", "Axosoft", "development", "logos:gitkraken"],
  ["TortoiseGit.TortoiseGit", "TortoiseGit", "development", "资源管理器中的 Git 客户端", "TortoiseGit", "development"],
  ["WinMerge.WinMerge", "WinMerge", "development", "文件与目录比较工具", "WinMerge", "development"],
  ["Microsoft.PowerShell", "PowerShell", "development", "跨平台自动化 Shell", "Microsoft", "development", "logos:powershell"],
  ["Microsoft.AzureCLI", "Azure CLI", "development", "Azure 命令行工具", "Microsoft", "development", "logos:microsoft-azure"],
  ["Amazon.AWSCLI", "AWS CLI", "development", "AWS 命令行工具", "Amazon", "development", "logos:aws"],
  ["Kubernetes.kubectl", "kubectl", "development", "Kubernetes 命令行客户端", "Kubernetes", "development", "logos:kubernetes"],
  ["Helm.Helm", "Helm", "development", "Kubernetes 包管理工具", "Helm", "development", "logos:helm"],
  ["Hashicorp.Terraform", "Terraform", "development", "基础设施即代码工具", "HashiCorp", "development", "logos:terraform-icon"],

  ["Valve.Steam", "Steam", "games", "游戏购买、下载与社区", "Valve", "games", "logos:steam"],
  ["EpicGames.EpicGamesLauncher", "Epic Games Launcher", "games", "Epic 游戏平台", "Epic Games", "games", "simple-icons:epicgames"],
  ["GOG.Galaxy", "GOG GALAXY", "games", "GOG 游戏管理平台", "GOG", "games", "simple-icons:gogdotcom"],
  ["Ubisoft.Connect", "Ubisoft Connect", "games", "育碧游戏平台", "Ubisoft", "games", "simple-icons:ubisoft"],
  ["ElectronicArts.EADesktop", "EA app", "games", "EA 游戏平台", "Electronic Arts", "games", "simple-icons:ea"],
  ["Blizzard.BattleNet", "Battle.net", "games", "暴雪游戏平台", "Blizzard", "games", "simple-icons:battledotnet"],
  ["Playnite.Playnite", "Playnite", "games", "统一管理本机游戏库", "Playnite", "games", "simple-icons:playnite"],
  ["HeroicGamesLauncher.HeroicGamesLauncher", "Heroic Games Launcher", "games", "开源多平台游戏启动器", "Heroic Games Launcher", "games", "simple-icons:heroicgameslauncher"],
  ["ItchIo.Itch", "itch", "games", "独立游戏平台", "itch.io", "games", "simple-icons:itchdotio"],
  ["PrismLauncher.PrismLauncher", "Prism Launcher", "games", "Minecraft 实例管理器", "Prism Launcher", "games", "simple-icons:prismlauncher"],
  ["Mojang.MinecraftLauncher", "Minecraft Launcher", "games", "Minecraft 官方启动器", "Mojang", "games", "simple-icons:minecraft"],
  ["MoonlightGameStreamingProject.Moonlight", "Moonlight", "games", "低延迟串流游戏客户端", "Moonlight", "games", "simple-icons:moonlight"],
  ["Parsec.Parsec", "Parsec", "games", "低延迟远程桌面与游戏", "Parsec", "games", "simple-icons:parsec"],
  ["Libretro.RetroArch", "RetroArch", "games", "开源复古游戏平台", "Libretro", "games", "simple-icons:retroarch"],
  ["PPSSPPTeam.PPSSPP", "PPSSPP", "games", "PSP 游戏模拟器", "PPSSPP Team", "games", "simple-icons:ppsspp"],
  ["PCSX2Team.PCSX2", "PCSX2", "games", "PlayStation 2 模拟器", "PCSX2 Team", "games", "simple-icons:pcsx2"],
  ["Cemu.Cemu", "Cemu", "games", "Wii U 模拟器", "Cemu", "games"],
  ["DolphinEmulator.Dolphin", "Dolphin Emulator", "games", "GameCube 与 Wii 模拟器", "Dolphin Emulator", "games", "simple-icons:dolphinemulator"],
  ["Amazon.Games", "Amazon Games", "games", "Amazon 游戏平台", "Amazon", "games", "simple-icons:amazonluna"],
  ["PlayStation.PSRemotePlay", "PS Remote Play", "games", "串流游玩 PlayStation 主机", "PlayStation", "games", "simple-icons:playstation"],
];

export const curatedApps: CuratedApp[] = rows.map(([id, name, category, description, publisher, section, icon]) => ({
  id,
  name,
  category,
  description,
  publisher,
  section,
  icon,
  version: "",
  source: "winget",
}));

export const discoverSections: { id: StoreSectionId; title: string; limit: number }[] = [
  { id: "domestic", title: "国内常用", limit: 14 },
  { id: "setup", title: "装机好帮手", limit: 18 },
  { id: "productivity", title: "办公与沟通", limit: 15 },
  { id: "creative", title: "影音与创作", limit: 12 },
  { id: "development", title: "开发工具", limit: 12 },
  { id: "games", title: "游戏平台", limit: 12 },
];
