const featureTitles: Record<string, string> = {
  DisableTelemetry: "关闭遥测、跟踪和定向广告",
  DisableSuggestions: "关闭 Windows 提示、技巧和建议内容",
  DisableNotifications: "关闭 Windows 应用通知",
  DisableLocationServices: "关闭定位服务和应用定位权限",
  DisableFindMyDevice: "关闭“查找我的设备”定位跟踪",
  DisableLockscreenTips: "关闭锁屏提示和技巧",
  DisableDesktopSpotlight: "关闭桌面 Windows 聚焦",
  DisableEdgeAds: "关闭 Edge 广告、建议和新闻流",
  DisableSettings365Ads: "隐藏设置主页中的 Microsoft 365 广告",
  DisableCopilot: "关闭 Microsoft Copilot",
  DisableRecall: "关闭 Windows Recall",
  DisableClickToDo: "关闭 Click to Do 和 AI 内容分析",
  DisableAISvcAutoStart: "阻止 Windows AI 服务自动启动",
  DisableEdgeAI: "关闭 Microsoft Edge AI 功能",
  DisablePaintAI: "关闭画图 AI 功能",
  DisableNotepadAI: "关闭记事本 AI 功能",
  DisableDVR: "关闭 Xbox 游戏录制",
  DisableGameBarIntegration: "关闭 Xbox Game Bar 集成",
  ClearStart: "清空当前用户的开始菜单固定项",
  ClearStartAllUsers: "清空所有用户的开始菜单固定项",
  DisableStartRecommended: "隐藏开始菜单推荐区域",
  DisableStartAllApps: "隐藏开始菜单“所有应用”区域",
  DisableStartPhoneLink: "关闭开始菜单中的手机连接",
  DisableBing: "关闭搜索中的 Bing 和 Copilot",
  DisableStoreSearchSuggestions: "关闭搜索中的 Microsoft Store 应用建议",
  StartAllAppsCategory: "所有应用使用分类视图",
  StartAllAppsGrid: "所有应用使用网格视图",
  StartAllAppsList: "所有应用使用列表视图",
  DisableSettingsHome: "隐藏 Windows 设置主页",
  EnableDarkMode: "启用系统和应用深色主题",
  DisableTransparency: "关闭透明效果",
  DisableAnimations: "关闭动画和视觉效果",
  DisableDragTray: "关闭文件拖拽分享托盘",
  RevertContextMenu: "使用 Windows 10 经典右键菜单",
  DisableMouseAcceleration: "关闭鼠标指针加速",
  DisableStickyKeys: "关闭连续按 Shift 启动粘滞键",
  DisableStorageSense: "关闭存储感知自动清理",
  DisableFastStartup: "关闭 Windows 快速启动",
  DisableBitlockerAutoEncryption: "关闭 BitLocker 自动设备加密",
  DisableModernStandbyNetworking: "关闭现代待机网络连接",
  DisableWindowSnapping: "关闭窗口贴靠",
  DisableSnapAssist: "关闭贴靠窗口应用建议",
  DisableSnapLayouts: "隐藏贴靠布局浮层",
  HideTabsInAltTab: "Alt+Tab 不显示应用标签页",
  Show3TabsInAltTab: "Alt+Tab 显示最近 3 个标签页",
  Show5TabsInAltTab: "Alt+Tab 显示最近 5 个标签页",
  Show20TabsInAltTab: "Alt+Tab 显示最近 20 个标签页",
  TaskbarAlignLeft: "任务栏左对齐",
  HideSearchTb: "隐藏任务栏搜索",
  ShowSearchIconTb: "任务栏显示搜索图标",
  ShowSearchLabelTb: "任务栏显示搜索图标和标签",
  ShowSearchBoxTb: "任务栏显示搜索框",
  HideTaskview: "隐藏任务栏任务视图按钮",
  DisableWidgets: "关闭任务栏和锁屏小组件",
  HideChat: "隐藏任务栏聊天图标",
  EnableEndTask: "任务栏右键菜单显示“结束任务”",
  EnableLastActiveClick: "启用任务栏“最后活动窗口”切换",
  CombineTaskbarAlways: "主屏始终合并任务栏按钮",
  CombineTaskbarWhenFull: "主屏任务栏满时合并按钮",
  CombineTaskbarNever: "主屏从不合并任务栏按钮",
  CombineMMTaskbarAlways: "副屏始终合并任务栏按钮",
  CombineMMTaskbarWhenFull: "副屏任务栏满时合并按钮",
  CombineMMTaskbarNever: "副屏从不合并任务栏按钮",
  MMTaskbarModeAll: "所有任务栏显示应用图标",
  MMTaskbarModeMainActive: "主任务栏和活动窗口所在任务栏显示图标",
  MMTaskbarModeActive: "仅在窗口所在任务栏显示图标",
  ExplorerToHome: "文件资源管理器默认打开主页",
  ExplorerToThisPC: "文件资源管理器默认打开此电脑",
  ExplorerToDownloads: "文件资源管理器默认打开下载",
  ExplorerToOneDrive: "文件资源管理器默认打开 OneDrive",
  ShowKnownFileExt: "显示已知文件类型的扩展名",
  ShowHiddenFolders: "显示隐藏文件、文件夹和驱动器",
  HideDupliDrive: "隐藏重复的可移动驱动器条目",
  HideHome: "隐藏资源管理器导航栏中的主页",
  HideGallery: "隐藏资源管理器导航栏中的图库",
  HideOnedrive: "隐藏资源管理器导航栏中的 OneDrive",
  Hide3dObjects: "隐藏此电脑中的 3D 对象文件夹",
  HideMusic: "隐藏此电脑中的音乐文件夹",
  AddFoldersToThisPC: "在此电脑中恢复常用文件夹",
  HideIncludeInLibrary: "隐藏右键菜单“包含到库中”",
  HideGiveAccessTo: "隐藏右键菜单“授予访问权限”",
  HideShare: "隐藏右键菜单“共享”",
  ShowDriveLettersFirst: "盘符显示在驱动器名称前",
  ShowDriveLettersLast: "盘符显示在驱动器名称后",
  ShowNetworkDriveLettersFirst: "网络驱动器盘符显示在名称前",
  HideDriveLetters: "隐藏所有驱动器盘符",
  DisableUpdateASAP: "不优先获取最新 Windows 更新",
  PreventUpdateAutoReboot: "登录期间阻止更新自动重启",
  DisableDeliveryOptimization: "关闭向其他电脑共享已下载更新",
  DisableDeviceAutoAppDownload: "阻止自动安装设备配套应用",
  DisableBraveBloat: "关闭 Brave AI、加密货币和资讯功能",
  EnableWindowsSandbox: "启用 Windows 沙盒",
  EnableWindowsSubsystemForLinux: "启用 Windows Subsystem for Linux",
};

const groupTitles: Record<string, string> = {
  SearchIcon: "任务栏搜索样式",
  MultiMon: "任务栏应用显示位置",
  CombineButtons: "主屏任务栏按钮合并方式",
  CombineMMButtons: "副屏任务栏按钮合并方式",
  ClearStart: "移除开始菜单固定应用",
  ExplorerLocation: "文件资源管理器打开位置",
  DriveLetterPosition: "驱动器盘符位置",
  ShowTabsInAltTab: "Alt+Tab 中显示的应用标签页",
  StartAllAppsView: "开始菜单“所有应用”视图",
};

const optionLabels: Record<string, string> = {
  "Show search box (Default)": "显示搜索框（默认）",
  "Show search icon and label": "显示搜索图标和标签",
  "Show search icon only": "仅显示搜索图标",
  Hide: "隐藏",
  "All taskbars (Default)": "所有任务栏（默认）",
  "Main taskbar and taskbar where window is open": "主任务栏和窗口所在任务栏",
  "Taskbar where window is open": "窗口所在任务栏",
  "Always (Default)": "始终（默认）",
  "When taskbar is full": "任务栏已满时",
  Never: "从不",
  "Remove for the selected user": "仅当前用户",
  "Remove for all users": "所有用户",
  "Home (Default)": "主页（默认）",
  "This PC": "此电脑",
  Downloads: "下载",
  OneDrive: "OneDrive",
  "Show drive letters after drive label (Default)": "盘符在名称后（默认）",
  "Show drive letters before drive label": "盘符在名称前",
  "Show network drive letters before drive label": "仅网络盘符在名称前",
  "Hide all drive letters": "隐藏所有盘符",
  "Don't show tabs": "不显示标签页",
  "Show 3 most recent tabs (Default)": "最近 3 个（默认）",
  "Show 5 most recent tabs": "最近 5 个",
  "Show 20 most recent tabs": "最近 20 个",
  "Category (Default)": "分类（默认）",
  Grid: "网格",
  List: "列表",
};

export const fallbackCategories = [
  "隐私与建议内容", "系统", "开始菜单与搜索", "AI 功能", "Windows 更新", "任务栏",
  "外观", "文件资源管理器", "游戏", "多任务", "可选 Windows 功能", "其他",
];

const featureImpacts: Record<string, string> = {
  DisableTelemetry: "关闭遥测、诊断数据收集、活动历史记录和应用启动跟踪，减少发送给 Microsoft 的设备和 usage 数据。Windows 预览体验成员可能需重新开启可选诊断数据才能接收更新。",
  DisableSuggestions: "移除 Windows 中的提示、技巧、提醒和同步提供商广告，并阻止建议应用的自动安装。",
  DisableNotifications: "关闭来自应用和其他发送方的原生 Windows 通知，包括 Discord、WhatsApp、Teams 和 Slack 等应用的通知。",
  DisableLocationServices: "关闭 Windows 定位服务并拒绝应用访问位置。使用策略锁定相关设置。",
  DisableFindMyDevice: "关闭“查找我的设备”功能，设备将无法通过 Microsoft 账户远程定位。",
  DisableLockscreenTips: "关闭锁屏界面上的提示和技巧。",
  DisableDesktopSpotlight: "关闭桌面 Windows 聚焦，桌面壁纸将不再每日自动更换为 Bing 图片。",
  DisableEdgeAds: "关闭 Microsoft Edge 中的广告、建议内容和新闻流。",
  DisableSettings365Ads: "隐藏 Windows 设置主页中的 Microsoft 365 广告横幅。",
  DisableCopilot: "卸载并禁用 Microsoft Copilot，Windows 内置 AI 助手将不可用。",
  DisableRecall: "关闭 Windows Recall，停止对用户操作的周期性截图和分析。",
  DisableClickToDo: "关闭 Click to Do 和 AI 内容分析，屏幕截图中的内容将不再被识别为可操作对象。",
  DisableAISvcAutoStart: "阻止 Windows AI 相关服务在开机时自动启动，可能影响 AI 功能的响应速度。",
  DisableEdgeAI: "关闭 Microsoft Edge 中的 AI 功能（如 Copilot 侧边栏、AI 写作助手等）。",
  DisablePaintAI: "关闭画图应用中的 AI 功能（如图像生成、AI 编辑工具）。",
  DisableNotepadAI: "关闭记事本中的 AI 功能（如 AI 重写、AI 摘要）。",
  DisableDVR: "关闭 Xbox 游戏录制，无法再使用 Win+G 录制游戏片段或截图。",
  DisableGameBarIntegration: "关闭 Xbox Game Bar 集成，游戏时不再弹出 Game Bar 覆盖层。",
  ClearStart: "清空当前用户开始菜单中的所有固定应用。开始菜单布局将恢复为默认。",
  ClearStartAllUsers: "清空所有用户开始菜单中的固定应用，需要管理员权限。",
  DisableStartRecommended: "隐藏开始菜单中的推荐区域，最近添加的应用和文件将不再显示。",
  DisableStartAllApps: "隐藏开始菜单“所有应用”区域，可能导致已安装应用难以查找。使用策略锁定设置。",
  DisableStartPhoneLink: "关闭开始菜单中的手机连接入口，不影响 Phone Link 应用本身。",
  DisableBing: "关闭 Windows 搜索中的 Bing 网页结果和 Copilot 集成，搜索仅返回本地结果。",
  DisableStoreSearchSuggestions: "关闭 Windows 搜索中的 Microsoft Store 应用建议。",
  StartAllAppsCategory: "开始菜单“所有应用”使用分类视图（默认），应用按类别分组显示。",
  StartAllAppsGrid: "开始菜单“所有应用”使用网格视图，应用以平铺方式显示。",
  StartAllAppsList: "开始菜单“所有应用”使用列表视图，应用以纵向列表显示。",
  DisableSettingsHome: "隐藏 Windows 设置主页，打开设置时直接进入上次访问的分类。",
  EnableDarkMode: "启用系统和应用的深色主题，窗口边框、菜单等将使用深色配色。",
  DisableTransparency: "关闭透明效果，任务栏、窗口等将使用纯色背景。",
  DisableAnimations: "关闭动画和视觉效果，窗口切换更干脆但视觉过渡感减弱。",
  DisableDragTray: "关闭文件拖拽分享托盘，无法通过拖拽文件到任务栏触发分享。",
  RevertContextMenu: "恢复 Windows 10 经典右键菜单，不再显示“显示更多选项”二级菜单。",
  DisableMouseAcceleration: "关闭鼠标指针加速，指针移动将与物理移动完全线性对应，适合 FPS 游戏玩家。",
  DisableStickyKeys: "关闭连续按 Shift 启动粘滞键功能，连按 Shift 将不再弹出粘滞键提示。",
  DisableStorageSense: "关闭存储感知自动清理，Windows 不再自动清理临时文件和回收站。",
  DisableFastStartup: "关闭 Windows 快速启动，关机后将完全关闭而非混合休眠，开机速度可能变慢。",
  DisableBitlockerAutoEncryption: "关闭 BitLocker 自动设备加密，新安装的 Windows 或新分区将不再自动加密。",
  DisableModernStandbyNetworking: "关闭现代待机（S0 低功耗空闲）时的网络连接，睡眠期间将断网以省电，可能影响消息接收。",
  DisableWindowSnapping: "关闭窗口贴靠，拖拽窗口到屏幕边缘将不再自动调整大小。",
  DisableSnapAssist: "关闭贴靠窗口应用建议，贴靠后不再显示其他窗口的可选缩略图。",
  DisableSnapLayouts: "隐藏贴靠布局浮层，悬停最大化按钮时不再显示贴靠位置选项。",
  HideTabsInAltTab: "Alt+Tab 切换时不显示应用标签页（如 Edge 浏览器标签页），仅显示主窗口。",
  Show3TabsInAltTab: "Alt+Tab 显示每个应用最近 3 个标签页（默认）。",
  Show5TabsInAltTab: "Alt+Tab 显示每个应用最近 5 个标签页。",
  Show20TabsInAltTab: "Alt+Tab 显示每个应用最近 20 个标签页。",
  TaskbarAlignLeft: "任务栏图标左对齐，开始按钮位于左下角（Windows 10 风格）。",
  HideSearchTb: "隐藏任务栏上的搜索框。",
  ShowSearchIconTb: "任务栏显示搜索图标（无文字）。",
  ShowSearchLabelTb: "任务栏显示搜索图标和“搜索”文字标签。",
  ShowSearchBoxTb: "任务栏显示完整搜索框（默认）。",
  HideTaskview: "隐藏任务栏上的任务视图按钮。",
  DisableWidgets: "关闭任务栏和锁屏小组件，天气、新闻等面板将不再可用。",
  HideChat: "隐藏任务栏聊天图标（Microsoft Teams Chat 入口）。",
  EnableEndTask: "在任务栏右键菜单中显示“结束任务”选项，可直接关闭卡死的应用而无需打开任务管理器。",
  EnableLastActiveClick: "启用任务栏“最后活动窗口”切换，点击应用图标时切换到该应用最后活动的窗口。",
  CombineTaskbarAlways: "主屏任务栏始终合并应用按钮（默认）。",
  CombineTaskbarWhenFull: "主屏任务栏在占满时才合并应用按钮。",
  CombineTaskbarNever: "主屏任务栏从不合并应用按钮，每个窗口独立显示。",
  CombineMMTaskbarAlways: "副屏任务栏始终合并应用按钮（默认）。",
  CombineMMTaskbarWhenFull: "副屏任务栏在占满时才合并应用按钮。",
  CombineMMTaskbarNever: "副屏任务栏从不合并应用按钮。",
  MMTaskbarModeAll: "所有任务栏都显示应用图标（默认）。",
  MMTaskbarModeMainActive: "主任务栏和窗口所在任务栏显示应用图标。",
  MMTaskbarModeActive: "仅在窗口所在的任务栏显示应用图标。",
  ExplorerToHome: "文件资源管理器默认打开“主页”（默认）。",
  ExplorerToThisPC: "文件资源管理器默认打开“此电脑”。",
  ExplorerToDownloads: "文件资源管理器默认打开“下载”文件夹。",
  ExplorerToOneDrive: "文件资源管理器默认打开 OneDrive。",
  ShowKnownFileExt: "显示已知文件类型的扩展名，便于识别文件格式。",
  ShowHiddenFolders: "显示隐藏的文件、文件夹和驱动器。",
  HideDupliDrive: "隐藏重复的可移动驱动器条目，避免 U 盘等设备显示两次。",
  HideHome: "隐藏资源管理器导航栏中的“主页”入口。",
  HideGallery: "隐藏资源管理器导航栏中的“图库”入口。",
  HideOnedrive: "隐藏资源管理器导航栏中的 OneDrive 入口。",
  Hide3dObjects: "隐藏“此电脑”中的 3D 对象文件夹。",
  HideMusic: "隐藏“此电脑”中的音乐文件夹。",
  AddFoldersToThisPC: "在“此电脑”中恢复桌面、文档、下载等常用文件夹的显示。",
  HideIncludeInLibrary: "隐藏右键菜单中的“包含到库中”选项。",
  HideGiveAccessTo: "隐藏右键菜单中的“授予访问权限”选项。",
  HideShare: "隐藏右键菜单中的“共享”选项。",
  ShowDriveLettersFirst: "盘符显示在驱动器名称之前。",
  ShowDriveLettersLast: "盘符显示在驱动器名称之后（默认）。",
  ShowNetworkDriveLettersFirst: "仅网络驱动器的盘符显示在名称前。",
  HideDriveLetters: "隐藏所有驱动器盘符。",
  DisableUpdateASAP: "不优先获取最新 Windows 更新，推迟到稳定渠道推送。",
  PreventUpdateAutoReboot: "在有用户登录期间阻止 Windows 更新自动重启电脑。",
  DisableDeliveryOptimization: "关闭向其他电脑共享已下载的更新内容，不再作为更新分发节点。",
  DisableDeviceAutoAppDownload: "阻止系统自动下载设备配套应用（如打印机、相机的厂商应用）。",
  DisableBraveBloat: "关闭 Brave 浏览器的 AI、加密货币和资讯功能。",
  EnableWindowsSandbox: "启用 Windows 沙盒，可在隔离环境中运行不可信应用。需要管理员权限。",
  EnableWindowsSubsystemForLinux: "启用 Windows Subsystem for Linux（WSL），可在 Windows 上运行 Linux 发行版。需要管理员权限。",
  SvchostSplitDisable: "设置 svchost 拆分数等于物理内存 GB，减少 svchost.exe 进程数量，降低低配机器的内存占用。恢复后回到系统默认的拆分策略。",
  DisableHPET: "禁用高精度事件计时器（HPET），在游戏场景下可降低输入延迟。部分老旧硬件可能不稳定，恢复后需重启。",
  UnlockCpuCores: "解除系统对 CPU 核心使用的限制，释放全部物理核心性能。恢复后回到系统默认的能耗策略，需重启生效。",
};

export function featureTitle(id: string, source: string) { return featureTitles[id] ?? source; }
export function groupTitle(id: string, source: string) { return groupTitles[id] ?? source; }
export function optionLabel(source: string) { return optionLabels[source] ?? source; }
export function featureImpact(id: string) { return featureImpacts[id]; }
