"""Vendor awesome-gpt-image-2's prompt method into focused Skill references."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

SECTIONS = {
    "tpl-ui": "templates-ui-interface.md",
    "tpl-infographic": "templates-infographic.md",
    "tpl-poster": "templates-poster-typography.md",
    "tpl-product": "templates-product-commerce.md",
    "tpl-brand": "templates-brand-logo.md",
    "tpl-architecture": "templates-architecture-space.md",
    "tpl-photo": "templates-photography-realism.md",
    "tpl-illustration": "templates-illustration-art.md",
    "tpl-character": "templates-character-people.md",
    "tpl-scene": "templates-scene-storytelling.md",
    "tpl-history": "templates-history-classical.md",
    "tpl-document": "templates-document-publishing.md",
    "tpl-other": "templates-other-use-cases.md",
}

SECTION_RE = re.compile(
    r'(?m)^<a name="(?P<anchor>tpl-[^"]+)"></a>\s*\n\s*### (?P<title>[^\n]+)'
)


def digest(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def sync(source: Path, target: Path) -> None:
    skill = source / "agents/skills/gpt-image-2-style-library/SKILL.md"
    style = source / "agents/skills/gpt-image-2-style-library/references/style-library.md"
    templates = source / "docs/templates.md"
    library_json = source / "data/style-library.json"
    cases_json = source / "data/cases.json"
    required = (skill, style, templates, library_json, cases_json, source / "LICENSE", source / "docs/disclaimer.md")
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise FileNotFoundError("missing upstream files: " + ", ".join(missing))

    template_text = templates.read_text(encoding="utf-8")
    matches = list(SECTION_RE.finditer(template_text))
    anchors = [match.group("anchor") for match in matches]
    if anchors != list(SECTIONS):
        raise ValueError(f"upstream template sections changed: {anchors}")

    library = json.loads(library_json.read_text(encoding="utf-8"))
    if len(library.get("templates", [])) != 22:
        raise ValueError("expected exactly 22 upstream style-library templates")
    cases_document = json.loads(cases_json.read_text(encoding="utf-8"))
    cases_by_id = {case["id"]: case for case in cases_document.get("cases", [])}

    header = (
        "<!-- Generated by scripts/sync_reference_project.py. "
        "Content below is preserved from awesome-gpt-image-2. -->\n\n"
    )
    write(target / "source-skill.md", header + skill.read_text(encoding="utf-8"))
    write(target / "style-library.md", header + style.read_text(encoding="utf-8"))
    (target / "style-library.json").write_bytes(library_json.read_bytes())
    (target / "cases.json").write_bytes(cases_json.read_bytes())
    write(target / "license.md", header + (source / "LICENSE").read_text(encoding="utf-8"))
    write(target / "disclaimer.md", header + (source / "docs/disclaimer.md").read_text(encoding="utf-8"))
    write(target / "templates-introduction.md", header + template_text[: matches[0].start()])

    rows = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(template_text)
        anchor = match.group("anchor")
        title = match.group("title").strip()
        filename = SECTIONS[anchor]
        write(target / filename, header + template_text[match.start() : end])
        rows.append((title, anchor, filename))

    template_rows = []
    for template in library["templates"]:
        example_ids = template.get("exampleCases", [])
        missing_cases = [case_id for case_id in example_ids if case_id not in cases_by_id]
        if missing_cases:
            raise ValueError(f"template {template['id']} references missing cases: {missing_cases}")
        filename = f"examples-{template['id']}.md"
        example_lines = [
            f"# {template['title'].get('zh') or template['title'].get('en')}：源项目示例提示词",
            "",
            "以下案例是源项目风格索引为本模板指定的示例。保留原提示词与来源信息；根据当前任务改写，不机械复制主题、品牌、事实或文字。",
            "",
        ]
        for case_id in example_ids:
            case = cases_by_id[case_id]
            example_lines.extend([
                f"## Case {case_id} — {case.get('title', '')}",
                "",
                f"- Category: {case.get('category', '')}",
                f"- Styles: {', '.join(case.get('styles', []))}",
                f"- Scenes: {', '.join(case.get('scenes', []))}",
                f"- Source: {case.get('sourceLabel', '')} {case.get('sourceUrl', '')}".rstrip(),
                f"- Gallery: {case.get('githubUrl', '')}",
                "",
                "````text",
                case.get("prompt", ""),
                "````",
                "",
            ])
        write(target / filename, "\n".join(example_lines))
        title = template["title"].get("zh") or template["title"].get("en") or template["id"]
        template_rows.append((title, template["id"], SECTIONS[template["anchor"]], filename))

    source_ref = library.get("repository", "https://github.com/freestylefly/awesome-gpt-image-2")
    index_lines = [
        "# awesome-gpt-image-2 原始提示词参考",
        "",
        "本目录完整保留参考项目的 Agent Skill、风格索引和 `docs/templates.md` 提示词方法。",
        "运行时先按图片类型读取下面一个模板文件；需要类别、风格、场景和案例 ID 时再读 `style-library.md`。",
        "这些文件是提示词方法的权威来源；Mona 的摘要和示例用于辅助理解，不能替代这里的完整模板。",
        "",
        "| 图片类型 | 原始锚点 | 按需读取 |",
        "|---|---|---|",
        *[f"| {title} | `{anchor}` | [{filename}]({filename}) |" for title, anchor, filename in rows],
        "",
        "## 22 个模板与指定示例",
        "",
        "| 模板 | ID | 完整方法 | 源项目示例提示词 |",
        "|---|---|---|---|",
        *[
            f"| {title} | `{template_id}` | [{template_file}]({template_file}) | [{example_file}]({example_file}) |"
            for title, template_id, template_file, example_file in template_rows
        ],
        "",
        "## 其它原始文件",
        "",
        "- [源项目 Skill](source-skill.md)",
        "- [完整风格与模板索引](style-library.md)",
        "- `style-library.json`：源项目结构化分类、风格、场景和 22 个模板",
        "- `cases.json`：源项目 541 条案例提示词、标签和来源；使用 `find_upstream_cases.py` 按需检索",
        "- [模板文档导言](templates-introduction.md)",
        "- [上游许可证](license.md)",
        "- [上游内容声明](disclaimer.md)",
        "",
        f"同步来源：{source_ref}",
        f"- source SKILL SHA-256: `{digest(skill.read_bytes())}`",
        f"- style-library SHA-256: `{digest(style.read_bytes())}`",
        f"- templates SHA-256: `{digest(templates.read_bytes())}`",
        f"- style-library JSON SHA-256: `{digest(library_json.read_bytes())}`",
        f"- cases JSON SHA-256: `{digest(cases_json.read_bytes())}`",
        "",
    ]
    write(target / "templates-index.md", "\n".join(index_lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("--target", type=Path, default=Path(__file__).parents[1] / "references/upstream")
    args = parser.parse_args()
    sync(args.source.resolve(), args.target.resolve())


if __name__ == "__main__":
    main()
