export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** Multi-agent author kinds (phase 0, multi-agent-development-guide 5.3). */
export type AuthorType = "user" | "agent" | "system";

/** Structured message kinds; plain conversation is ``message``. */
export type MessageType = "message" | "job_status" | "workflow_run" | "approval" | "artifact";

/** Conversation shapes (multi-agent phase 2, guide 5.2). */
export type ConversationType = "direct" | "room";

/** Conversation metadata mirrored from ``Session.metadata["conversation"]``
 * (camelCase, matching the backend ``by_alias=True`` dump). Legacy sessions
 * without this payload are treated as a direct chat with Mona. */
export interface ConversationMeta {
  schemaVersion?: number;
  type: ConversationType;
  title: string;
  goal?: string | null;
  agentIds: string[];
  directAgentId?: string | null;
  activeWorkflowId?: string | null;
  activeWorkflowRevision?: number | null;
  archived?: boolean;
}

/** Agent listing entry (``GET /api/agents``). */
export interface AgentSummary {
  id: string;
  displayName: string;
  avatarUrl?: string;
  description: string;
  enabled: boolean;
}

/** One member entry inside a room state payload. */
export interface RoomAgentInfo {
  id: string;
  displayName: string;
  description: string;
}

/** Room state returned by ``create_room`` / ``update_room`` / ``get_room_state``
 * results and pushed via ``room_updated`` events. */
export interface RoomState {
  conversation: ConversationMeta;
  agents: RoomAgentInfo[];
}

/** Job states mirrored from ``mona/agent/jobs.py`` (guide 5.6). */
export type AgentJobStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled";

/** Compact job projection carried by ``agent_job_updated`` events. */
export interface AgentJobSummary {
  id: string;
  roomId: string;
  requestedBy: string;
  assignedTo: string;
  task: string;
  status: AgentJobStatus;
  workflowRunId?: string | null;
  workflowStepId?: string | null;
  parentJobId?: string | null;
  attempt?: number;
  result?: string | null;
  error?: string | null;
}

/** Editable room fields accepted by the ``update_room`` command. */
export interface RoomUpdate {
  title?: string;
  goal?: string | null;
  agentIds?: string[];
}

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface DeliveredFile {
  path: string;
  absolute_path: string;
  name: string;
  size: number;
  size_human: string;
  mime: string;
  summary?: string;
  /** ISO 8601 timestamp from the shared-output scan. May be absent on
   *  deliver_file/file_edit events that don't carry mtime. */
  modified_at?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  /** Short display text for user messages (e.g. action label). Falls back to ``content``. */
  displayContent?: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** Activity rows: explicit file edits emitted by edit tools. */
  fileEdits?: UIFileEdit[];
  /** Activity rows created during the same agent phase share one collapsible block. */
  activitySegmentId?: string;
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Files delivered via deliver_file tool, rendered as FileCards. */
  deliveredFiles?: DeliveredFile[];
  /** Assistant turn: accumulated model reasoning / thinking text. Built up
   * incrementally from ``reasoning_delta`` frames; finalized when
   * ``reasoning_end`` arrives. */
  reasoning?: string;
  /** True while ``reasoning_delta`` frames are still arriving for this turn.
   * Drives the shimmer header on ``ReasoningBubble``. */
  reasoningStreaming?: boolean;
  /** End-to-end wall time for this assistant turn (persisted ``latency_ms`` / ``turn_end``). */
  latencyMs?: number;
  /** User turn: true when this message was injected mid-turn (via the pending
   *  queue "append" action) rather than sent as a new conversational turn.
   *  Drives a subtle visual badge so the user knows it was a supplement. */
  isInjected?: boolean;
  /** Multi-agent phase 0: who authored this message. Absent on
   *  pre-multi-agent persisted data. */
  authorType?: AuthorType;
  /** Agent ID of the author (``mona``, ``com.mona.a-share-analyst``, …).
   *  Absent on user messages and legacy data; render a missing value on
   *  assistant messages as Mona. */
  authorId?: string;
  /** Structured message kind; plain conversation when absent or ``message``. */
  messageType?: MessageType;
  /** Delegated job this message belongs to (``job_status`` / delegated replies). */
  jobId?: string;
  /** Workflow run this message belongs to (``workflow_run`` / ``approval``). */
  workflowRunId?: string;
  /** Structured payload for non-``message`` kinds (job snapshot, run summary…). */
  payload?: unknown;
}

/** Structured UI blob on ``progress`` WS frames; channels may add more ``kind`` values later. */
export interface AgentUIBlob {
  kind: string;
  data?: unknown;
}

/** WebSocket snapshot for sustained goals (`goal_state` events; keyed by ``chat_id``). */
export interface GoalStateWsPayload {
  active: boolean;
  ui_summary?: string;
  objective?: string;
}

export interface ToolProgressEvent {
  version?: number;
  phase?: "start" | "end" | "error" | string;
  call_id?: string;
  name?: string;
  arguments?: unknown;
  result?: unknown;
  error?: unknown;
  files?: unknown[];
  embeds?: unknown[];
}

export interface UIFileEdit {
  version?: number;
  call_id: string;
  tool: string;
  path: string;
  absolute_path?: string;
  phase?: "start" | "end" | "error" | string;
  added: number;
  deleted: number;
  approximate?: boolean;
  status: "editing" | "done" | "error";
  binary?: boolean;
  error?: string;
  pending?: boolean;
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
  /** Project workspace directory bound to this session. ``null`` (or omitted)
   *  means the session belongs to the default "会话" section (default workspace). */
  workspace?: string | null;
  /** Unix epoch seconds when this session currently has a turn in flight. */
  runStartedAt?: number | null;
}

export type SidebarDensity = "comfortable" | "compact";
export type SidebarSortMode = "updated_desc" | "created_desc" | "title_asc";

export interface SidebarViewState {
  density: SidebarDensity;
  show_previews: boolean;
  show_timestamps: boolean;
  show_archived: boolean;
  sort: SidebarSortMode;
}

export interface SidebarStatePayload {
  schema_version: number;
  pinned_keys: string[];
  archived_keys: string[];
  title_overrides: Record<string, string>;
  tags_by_key: Record<string, string[]>;
  collapsed_groups: Record<string, boolean>;
  view: SidebarViewState;
  updated_at?: string | null;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
    model_preset: string | null;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    timezone: string;
    bot_name: string;
    bot_icon: string;
    tool_hint_max_length: number;
  };
  model_presets: Array<{
    name: string;
    label: string;
    active: boolean;
    is_default: boolean;
    model: string;
    provider: string;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    capabilities?: {
      supports_vision: boolean | null;
      supports_tool_calling: boolean | null;
      supports_streaming: boolean;
      supports_json_mode: boolean | null;
    };
  }>;
  providers: Array<{
    name: string;
    label: string;
    configured: boolean;
    api_key_required?: boolean;
    api_key_hint?: string | null;
    api_base?: string | null;
    default_api_base?: string | null;
    free_default_model?: string | null;
    model?: string | null;
    backend?: string;
    probe_supported?: boolean;
  }>;
  web_search: {
    provider: string;
    api_key_hint?: string | null;
    base_url?: string | null;
    max_results: number;
    timeout: number;
    providers: Array<{
      name: string;
      label: string;
      credential: "none" | "api_key" | "base_url";
    }>;
  };
  web: {
    enable: boolean;
    proxy?: string | null;
    user_agent?: string | null;
    search: {
      max_results: number;
      timeout: number;
    };
    fetch: {
      use_jina_reader: boolean;
    };
  };
  image_generation: {
    enabled: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    default_aspect_ratio: string;
    default_image_size: string;
    max_images_per_turn: number;
    save_dir: string;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
      image_models?: string[];
      default_image_model?: string | null;
    }>;
  };
  video_generation: {
    enabled: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    default_aspect_ratio: string;
    default_duration: number;
    save_dir: string;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
      video_models?: string[];
      default_video_model?: string | null;
    }>;
  };
  runtime: {
    config_path: string;
    workspace_path: string;
    gateway_host: string;
    gateway_port: number;
    heartbeat: {
      enabled: boolean;
      interval_s: number;
      keep_recent_messages: number;
    };
    dream: {
      schedule: string;
      max_batch_size: number;
      max_iterations: number;
      annotate_line_ages: boolean;
    };
    unified_session: boolean;
  };
  advanced: {
    restrict_to_workspace: boolean;
    ssrf_whitelist_count: number;
    mcp_server_count: number;
    exec_enabled: boolean;
    exec_sandbox?: string | null;
    exec_path_append_set: boolean;
  };
  channels: {
    available: Array<ChannelInfo>;
  };
  tts: {
    provider: string;
    voice: string;
    api_base: string | null;
    model: string | null;
    api_key_configured: boolean;
    api_key_hint: string | null;
  };
  requires_restart: boolean;
  restart_required_sections?: Array<"runtime" | "web" | "image" | "channels">;
}

export interface ChannelInfo {
  name: string;
  display_name: string;
  enabled: boolean;
  supports_login: boolean;
  logged_in?: boolean;
  allow_from?: string[];
  /** WeCom: bot_id; QQ/Feishu: app_id. */
  bot_id?: string;
  app_id?: string;
  /** "true" if a secret/app_secret is set, "" otherwise (never echoes the value). */
  secret?: string;
  app_secret?: string;
}

export type WeixinLoginState =
  | "idle"
  | "fetching_qr"
  | "awaiting_scan"
  | "confirmed"
  | "expired"
  | "failed"
  | "cancelled";

export interface WeixinLoginStatus {
  state: WeixinLoginState;
  qr_svg?: string;
  error?: string;
  logged_in?: boolean;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
  modelPreset?: string | null;
  providerModel?: string;
  timezone?: string;
  botName?: string;
  botIcon?: string;
  toolHintMaxLength?: number;
  workspace?: string;
}

export interface ProviderSettingsUpdate {
  provider: string;
  apiKey?: string;
  apiBase?: string;
  model?: string;
}

export interface WebSearchSettingsUpdate {
  provider: string;
  apiKey?: string;
  baseUrl?: string;
  maxResults?: number;
  timeout?: number;
  useJinaReader?: boolean;
}

export interface ImageGenerationSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  defaultAspectRatio: string;
  defaultImageSize: string;
  maxImagesPerTurn: number;
}

export interface VideoGenerationSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  defaultAspectRatio: string;
  defaultDuration: number;
}

export interface TtsSettingsUpdate {
  provider?: string;
  voice?: string;
  apiBase?: string;
  model?: string;
  /** Non-empty replaces the stored key; omitted leaves it unchanged. */
  apiKey?: string;
  /** Remove the stored API key. */
  clearKey?: boolean;
}

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      tool_events?: ToolProgressEvent[];
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress" | "reasoning";
      /** Server-measured turn wall time when this frame finishes an assistant reply. */
      latency_ms?: number;
      /** Optional structured payload on progress frames (channel-specific). */
      agent_ui?: AgentUIBlob;
      /** Set when this message is a fired personal schedule reminder;
       * webui clients use it to trigger a native system notification. */
      schedule_reminder?: boolean;
      schedule_item_id?: string;
    }
  | {
      event: "file_edit";
      chat_id: string;
      edits: UIFileEdit[];
    }
  | {
      event: "deliver_files";
      chat_id: string;
      files: DeliveredFile[];
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
    }
  | {
      event: "reasoning_delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "reasoning_end";
      chat_id: string;
      stream_id?: string;
    }
  | {
      event: "runtime_model_updated";
      model_name: string;
      model_preset?: string | null;
    }
  | {
      event: "turn_end";
      chat_id: string;
      latency_ms?: number;
      /** Authoritative sustained-goal snapshot for this chat (same shape as ``goal_state`` events). */
      goal_state?: GoalStateWsPayload;
    }
  | {
      event: "goal_status";
      chat_id: string;
      /** Turn executing (user message through agent loop). */
      status: "running" | "idle";
      /** Server ``time.time()`` when ``status`` is ``running``. */
      started_at?: number;
    }
  | {
      event: "goal_state";
      chat_id: string;
      goal_state: GoalStateWsPayload;
    }
  | { event: "session_updated"; chat_id: string; scope?: "metadata" | "thread" | string }
  | { event: "artifacts_changed" }
  | { event: "error"; chat_id?: string; detail?: string }
  | {
      event: "ppt_upload_result";
      ok: boolean;
      files?: { name: string; path: string }[];
      error?: string;
    }
  | {
      event: "ppt_save_brand_result";
      ok: boolean;
      brandId?: string;
      error?: string;
    }
  | {
      event: "ppt_delete_brand_result";
      ok: boolean;
      brandId?: string;
      error?: string;
    }
  | {
      event: "ppt_import_native_result";
      ok: boolean;
      templateId?: string;
      name?: string;
      pageCount?: number;
      coverUrl?: string;
      primaryColor?: string;
      error?: string;
    }
  | {
      event: "ppt_delete_native_result";
      ok: boolean;
      templateId?: string;
      error?: string;
    }
  | {
      event: "doc_upload_result";
      ok: boolean;
      files?: { name: string; path: string; size?: number; mime?: string }[];
      chat_id?: string;
      error?: string;
    };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

/** Response shape for ``GET .../webui-thread`` (server-built transcript replay). */
export interface WebuiThreadPersistedPayload {
  schemaVersion: number;
  sessionKey?: string;
  savedAt?: string;
  messages: UIMessage[];
}

export type Outbound =
  | { type: "new_chat"; ephemeral?: boolean; workspace?: string | null; agent_kind?: string | null }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      webui?: true;
      /** IMPORTANT: Short display text for the user message bubble (e.g. action label).
       *  When set, the frontend renders this instead of the full `content`.
       *  This field is persisted to the server so history replay also shows the short version.
       *  DO NOT remove — multiple modules (terminal, db, notes) depend on this. */
      display_content?: string;
      terminal_session_id?: string;
      terminal_exec_mode?: string;
      db_connection_id?: string;
      db_database?: string;
      db_table?: string;
      db_type?: string;
      db_server_version?: string;
      db_current_sql?: string;
      db_last_error?: string;
      browser_page_url?: string;
      browser_page_title?: string;
    }
  | { type: "delete_chat"; chat_id: string }
  | {
      type: "ppt_upload";
      files: { name: string; data_url: string }[];
    }
  | {
      type: "ppt_delete_brand";
      data: { brandId: string };
    }
  | {
      type: "ppt_import_native";
      file: { name: string; data_url: string };
    }
  | {
      type: "ppt_delete_native";
      data: { templateId: string };
    }
  | {
      type: "doc_upload";
      chat_id: string;
      files: { name: string; data_url: string }[];
    };

export interface PptTemplate {
  key: string;
  kind: "layout" | "brand" | "native";
  group: string;
  name: string;
  summary: string;
  coverSvgUrl: string;
  primaryColor?: string;
  pageCount?: number;
  canvasFormat?: string;
  userCreated?: boolean;
}

export interface PptCanvasFormat {
  key: string;
  label: string;
  viewBox: string;
  desc: string;
}

export interface PptTemplatesResponse {
  templates: PptTemplate[];
  canvasFormats: PptCanvasFormat[];
}

export interface PptProject {
  name: string;
  createdAt: number;
  format: string;
  slideCount: number;
  hasExport: boolean;
  hasSvgOutput: boolean;
  hasPptxOutput: boolean;
  hasSpecLock: boolean;
  status: "init" | "planning" | "generating" | "done";
  phase?: string;
  chatId: string | null;
}

