"""Source provenance records (design §7.3).

Every piece of fetched data carries a :class:`SourceRecord` generated by the
data layer — agents may reference sources but never fabricate them. The
content hash lets a report reader verify the record against the raw payload
kept in the evidence cache.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timedelta, timezone
from typing import Any

from pydantic import Field

from mona.config.schema import Base

CN_TZ = timezone(timedelta(hours=8))  # Asia/Shanghai (fixed offset, no DST)


def parse_asia_datetime(value: Any) -> datetime | None:
    """Parse a supported timestamp as an Asia/Shanghai-aware datetime.

    Date-only and timezone-naive values are interpreted in the A-share
    timezone.  Values that do not match a supported representation return
    ``None`` so callers can record unknown availability instead of guessing
    whether the value is before or after a research cutoff.
    """
    if isinstance(value, datetime):
        parsed = value
    elif isinstance(value, str):
        raw = value.strip()
        if not raw:
            return None
        try:
            parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        except ValueError:
            for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
                try:
                    parsed = datetime.strptime(raw, fmt)
                    break
                except ValueError:
                    parsed = None
            if parsed is None:
                return None
    else:
        return None

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=CN_TZ)
    return parsed.astimezone(CN_TZ)


def normalize_asia_datetime(value: Any) -> str | None:
    """Return a canonical ISO timestamp, or ``None`` when it is unknown."""
    parsed = parse_asia_datetime(value)
    return parsed.isoformat() if parsed is not None else None


def compare_asia_datetime(value: Any, cutoff: Any) -> bool | None:
    """Return whether ``value`` is at or before ``cutoff``.

    ``None`` means one side could not be parsed; callers must not treat it as
    either future or past.
    """
    parsed_value = parse_asia_datetime(value)
    parsed_cutoff = parse_asia_datetime(cutoff)
    if parsed_value is None or parsed_cutoff is None:
        return None
    return parsed_value <= parsed_cutoff


class SourceRecord(Base):
    """Where a piece of data came from and when (design §7.3 JSON shape)."""

    id: str  # deterministic: "src_" + sha256[:12] of the raw body
    provider: str
    url: str
    published_at: str | None = None  # public availability/observation time
    period_end: str | None = None  # statistical/reporting period end
    fetched_at: str
    content_hash: str  # "sha256:<hex>" of the raw response body
    fields: list[str] = Field(default_factory=list)  # extracted field names

    @classmethod
    def create(
        cls,
        *,
        provider: str,
        url: str,
        body: bytes,
        fields: list[str],
        published_at: str | None = None,
        period_end: str | None = None,
        fetched_at: str | None = None,
    ) -> "SourceRecord":
        digest = hashlib.sha256(body).hexdigest()
        return cls(
            id=f"src_{digest[:12]}",
            provider=provider,
            url=url,
            published_at=published_at,
            period_end=period_end,
            fetched_at=fetched_at or datetime.now(CN_TZ).isoformat(),
            content_hash=f"sha256:{digest}",
            fields=list(fields),
        )
