"""Validation for Mona's dedicated AlphaTex guitar tablature format."""

from __future__ import annotations

import hashlib
import json
import re
from fractions import Fraction
from typing import Any

from mona.agent.tools.base import tool_parameters
from mona.agent.tools.filesystem import _FsTool
from mona.agent.tools.schema import IntegerSchema, StringSchema, tool_parameters_schema

_SECTION_RE = re.compile(r"(?m)^\s*\.\s*$")
_TIME_SIGNATURE_RE = re.compile(r"\\ts\s*\(\s*(\d+)\s+(\d+)\s*\)", re.IGNORECASE)
_TUNING_RE = re.compile(r"\\tuning\s*\(([^)]*)\)", re.IGNORECASE)
_STAFF_RE = re.compile(r"\\staff\s*\{([^}]*)\}", re.IGNORECASE)
_EFFECT_BLOCK = r"\{[^{}]*\}"
_NOTE_TOKEN = rf"(?:\d{{1,2}}|x)\.[1-6](?:\s*{_EFFECT_BLOCK})?"
_CHORD_TOKEN = rf"\({_NOTE_TOKEN}(?:\s+{_NOTE_TOKEN})*\)"
_BEAT_RE = re.compile(
    rf"(?P<beat>{_CHORD_TOKEN}|{_NOTE_TOKEN}|r)"
    r"\.(?P<duration>32|16|8|4|2|1)"
    r"(?:\s*\{(?P<effects>[^{}]*)\})?",
    re.IGNORECASE,
)
_NOTE_RE = re.compile(
    r"(?P<fret>\d{1,2}|x)\.(?P<string>[1-6])"
    r"(?:\s*\{(?P<effects>[^{}]*)\})?",
    re.IGNORECASE,
)
_BAR_METADATA_RE = re.compile(
    r"\\(?:ts|beaming)\s*\([^)]*\)|\\(?:section|tempo)\s+(?:\([^)]*\)|\"[^\"]*\"|'[^']*'|\S+)",
    re.IGNORECASE,
)

_NOTE_EFFECTS = frozenset({"h", "sl", "ss", "pm", "lr", "v", "b", "t", "ac"})
_BEAT_EFFECTS = frozenset({"ch", "sd", "su", "d", "dy"})
_EFFECT_IDENTIFIER_RE = re.compile(r"[A-Za-z][A-Za-z0-9_]*")
_BEND_VALUES_RE = re.compile(r"\(\s*[+-]?\d+(?:\s+[+-]?\d+)+\s*\)")


def _parse_effects(raw: str) -> tuple[list[str], str | None]:
    """Parse only the effect argument forms supported by this validator."""
    names: list[str] = []
    cursor = 0
    while cursor < len(raw):
        while cursor < len(raw) and raw[cursor].isspace():
            cursor += 1
        if cursor == len(raw):
            break
        identifier = _EFFECT_IDENTIFIER_RE.match(raw, cursor)
        if identifier is None:
            return names, "效果属性必须使用字母标识符。"
        name = identifier.group(0).lower()
        cursor = identifier.end()
        if name in names:
            return names, f"效果属性 {name} 不能重复。"
        names.append(name)

        if name == "ch":
            while cursor < len(raw) and raw[cursor].isspace():
                cursor += 1
            if cursor == len(raw) or raw[cursor] not in {'\"', "'"}:
                return names, 'ch 必须跟随非空引号和弦名，如 ch "Am"。'
            quote = raw[cursor]
            cursor += 1
            value_chars: list[str] = []
            while cursor < len(raw):
                char = raw[cursor]
                if char == "\\" and cursor + 1 < len(raw):
                    value_chars.extend((char, raw[cursor + 1]))
                    cursor += 2
                    continue
                if char == quote:
                    break
                value_chars.append(char)
                cursor += 1
            if cursor == len(raw) or raw[cursor] != quote:
                return names, "ch 的引号和弦名没有闭合。"
            if not "".join(value_chars).strip():
                return names, "ch 必须跟随非空引号和弦名。"
            cursor += 1
        elif name == "b":
            while cursor < len(raw) and raw[cursor].isspace():
                cursor += 1
            bend = _BEND_VALUES_RE.match(raw, cursor)
            if bend is None:
                return names, "b 只支持至少两个整数构成的曲线，如 b (0 4)。"
            cursor = bend.end()
        elif name == "dy":
            dynamic = re.match(r"\s+(ppp|pp|p|mp|mf|fff|ff|f)\b", raw[cursor:], re.IGNORECASE)
            if dynamic is None:
                return names, "dy 必须跟随力度 ppp、pp、p、mp、mf、f、ff 或 fff。"
            cursor += dynamic.end()

    if not names:
        return names, "效果属性块不能为空。"
    return names, None


def _effect_error(raw: str, allowed: frozenset[str], level: str) -> str | None:
    names, parse_error = _parse_effects(raw)
    if parse_error is not None:
        return parse_error
    for name in names:
        if name == "p":
            return "不支持属性 p；AlphaTex 中 p 是贝斯 pop，勾弦请使用 h。"
        if name not in allowed:
            return f"不支持{level}属性 {name}。"
    return None


def _without_comments(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    return re.sub(r"//[^\r\n]*", "", source)


def validate_guitar_tab(source: str, *, expected_bars: int | None = None) -> dict[str, Any]:
    """Validate the small AlphaTex subset generated by the guitar-tab Skill."""
    issues: list[dict[str, Any]] = []
    cleaned = _without_comments(source)
    sections = _SECTION_RE.split(cleaned, maxsplit=1)
    if len(sections) != 2:
        issues.append({
            "code": "missing_body_separator",
            "message": "六线谱头部与谱面之间必须有单独一行的句点（.）。",
        })
        header, body = cleaned, ""
    else:
        header, body = sections

    for tag, label in (("title", "标题"), ("track", "吉他轨道")):
        if not re.search(rf"\\{tag}\s+['\"][^'\"]+['\"]", header, re.IGNORECASE):
            issues.append({"code": f"missing_{tag}", "message": f"缺少 {label}元数据 \\{tag}。"})

    staff = _STAFF_RE.search(header)
    if staff is None or "tabs" not in {value.lower() for value in staff.group(1).split()}:
        issues.append({"code": "missing_tab_staff", "message": "必须声明 \\staff {tabs}，只渲染六线谱。"})

    tuning = _TUNING_RE.search(header)
    strings = tuning.group(1).split() if tuning else []
    if len(strings) != 6:
        issues.append({"code": "invalid_tuning", "message": "\\tuning 必须按高音弦到低音弦声明六根弦。"})

    meter_match = _TIME_SIGNATURE_RE.search(body)
    meter: Fraction | None = None
    if meter_match is None:
        issues.append({"code": "missing_time_signature", "message": "第一小节必须声明拍号，如 \\ts (4 4)。"})
    else:
        numerator, denominator = map(int, meter_match.groups())
        if numerator < 1 or numerator > 12 or denominator not in {1, 2, 4, 8, 16}:
            issues.append({"code": "invalid_time_signature", "message": "拍号超出支持范围。"})
        else:
            meter = Fraction(numerator, denominator)

    if body.strip() and not body.rstrip().endswith("|"):
        issues.append({"code": "unterminated_score", "message": "最后一小节必须以 | 结束。"})

    measures = body.split("|")
    if measures and not measures[-1].strip():
        measures.pop()
    beat_count = 0
    previous_notes: dict[str, str] = {}
    for measure_index, raw_measure in enumerate(measures, start=1):
        measure = _BAR_METADATA_RE.sub("", raw_measure)
        cursor = 0
        duration = Fraction()
        while cursor < len(measure):
            if measure[cursor].isspace():
                cursor += 1
                continue
            match = _BEAT_RE.match(measure, cursor)
            if match is None:
                issues.append({
                    "code": "unsupported_syntax",
                    "message": "不支持的 AlphaTex 六线谱语法。",
                    "measure": measure_index,
                    "column": cursor + 1,
                })
                break
            beat_count += 1
            beat = match.group("beat")
            strings_in_beat: set[str] = set()
            current_notes: dict[str, str] = {}
            for note in _NOTE_RE.finditer(beat):
                string = note.group("string")
                fret = note.group("fret").lower()
                current_notes[string] = fret
                note_effects = note.group("effects")
                if note_effects is not None:
                    effect_error = _effect_error(note_effects, _NOTE_EFFECTS, "音符")
                    if effect_error is not None:
                        issues.append({
                            "code": "unsupported_effect",
                            "message": effect_error,
                            "measure": measure_index,
                        })
                    else:
                        names, _ = _parse_effects(note_effects)
                        if "t" in names and (fret == "x" or previous_notes.get(string) != fret):
                            issues.append({
                                "code": "invalid_tie",
                                "message": "延音 t 必须接续前一拍同弦同品的实音，不能从休止或其它品位接续。",
                                "measure": measure_index,
                                "string": int(string),
                            })

            beat_effects = match.group("effects")
            parsed_beat_effects: list[str] = []
            if beat_effects is not None:
                effect_error = _effect_error(beat_effects, _BEAT_EFFECTS, "拍")
                if effect_error is not None:
                    issues.append({
                        "code": "unsupported_effect",
                        "message": effect_error,
                        "measure": measure_index,
                    })
                else:
                    parsed_beat_effects, _ = _parse_effects(beat_effects)

            # Effect contents can contain bend numbers, so inspect notes after
            # removing their already-validated note-level blocks.
            notes_without_effects = re.sub(_EFFECT_BLOCK, "", beat)
            for note in _NOTE_RE.finditer(notes_without_effects):
                fret = note.group("fret").lower()
                string = note.group("string")
                if string in strings_in_beat:
                    issues.append({
                        "code": "duplicate_string",
                        "message": "同一拍内同一根弦不能出现多个品位。",
                        "measure": measure_index,
                    })
                strings_in_beat.add(string)
                if fret != "x" and int(fret) > 36:
                    issues.append({
                        "code": "fret_out_of_range",
                        "message": "品位必须在 0–36 之间。",
                        "measure": measure_index,
                    })
            beat_duration = Fraction(1, int(match.group("duration")))
            if parsed_beat_effects.count("d") == 1:
                beat_duration *= Fraction(3, 2)
            duration += beat_duration
            previous_notes = current_notes
            cursor = match.end()
        if meter is not None and duration != meter:
            issues.append({
                "code": "measure_duration_mismatch",
                "message": f"第 {measure_index} 小节时值为 {duration}，应为 {meter}。",
                "measure": measure_index,
            })

    if beat_count == 0:
        issues.append({"code": "missing_music", "message": "六线谱没有可演奏内容。"})
    if expected_bars is not None and len(measures) != expected_bars:
        issues.append({
            "code": "bar_count_mismatch",
            "message": f"六线谱共有 {len(measures)} 小节，应为 {expected_bars} 小节。",
        })

    return {
        "ok": not issues,
        "issues": issues,
        "summary": {
            "sha256": hashlib.sha256(source.encode("utf-8")).hexdigest(),
            "barCount": len(measures),
            "beatCount": beat_count,
            "stringCount": len(strings),
        },
    }


@tool_parameters(
    tool_parameters_schema(
        path=StringSchema("Workspace-relative path to the UTF-8 .atex guitar tablature."),
        expected_bars=IntegerSchema(
            description="Expected bar count when the request specifies one.",
            minimum=1,
            maximum=256,
            nullable=True,
        ),
        required=["path"],
    )
)
class GuitarTabTool(_FsTool):
    """Validate Mona's dedicated AlphaTex guitar tablature subset."""

    _scopes = {"core", "subagent"}
    agent_allowlist = frozenset({"com.mona.musician"})

    @property
    def name(self) -> str:
        return "guitar_tab"

    @property
    def description(self) -> str:
        return (
            "Validate a workspace .atex guitar tablature before delivery. "
            "Returns exact structure, timing, fret, and bar-count errors."
        )

    @property
    def read_only(self) -> bool:
        return True

    async def execute(
        self,
        path: str,
        expected_bars: int | None = None,
        **kwargs: Any,
    ) -> str:
        try:
            tab_path = self._resolve(path)
        except (OSError, PermissionError, ValueError) as exc:
            return json.dumps({
                "ok": False,
                "issues": [{"code": "path_not_allowed", "message": str(exc)}],
            }, ensure_ascii=False)
        if tab_path.suffix.lower() != ".atex":
            return json.dumps({
                "ok": False,
                "issues": [{"code": "invalid_file_type", "message": "只接受 .atex 六线谱文件。"}],
            }, ensure_ascii=False)
        try:
            source = tab_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            return json.dumps({
                "ok": False,
                "issues": [{"code": "file_not_found", "message": "六线谱文件不存在。"}],
            }, ensure_ascii=False)
        except UnicodeDecodeError:
            return json.dumps({
                "ok": False,
                "issues": [{"code": "invalid_encoding", "message": "六线谱必须为 UTF-8 文本。"}],
            }, ensure_ascii=False)
        return json.dumps(
            validate_guitar_tab(source, expected_bars=expected_bars),
            ensure_ascii=False,
        )


__all__ = ["GuitarTabTool", "validate_guitar_tab"]
